=== leitelveintcbg/TestTMGit/TestTMGit/.stylesheets/stylesheet_config.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" > 

  <xsd:element name="stylesheetConfig">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="stylesheet" minOccurs="0" maxOccurs="unbounded" type="tStylesheet"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <!-- definition of Stylesheet  -->
  <xsd:complexType name="tStylesheet">
    <xsd:sequence>
      <xsd:element name="description" type="xsd:string" />
    </xsd:sequence>
    <xsd:attribute name="xslFile" use="required" type="xsd:string" />
    <xsd:attribute name="inputExtension" type="xsd:string" />
    <xsd:attribute name="resultExtension" use="required" type="xsd:string" />
    <xsd:attribute name="aggregatorClass" use="required" type="xsd:string" />
  </xsd:complexType>

</xsd:schema>

=== leitelveintcbg/TestTMGit/TestTMGit/.stylesheets/stylesheet_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<stylesheetConfig xmlns:xe="http://www.alvicom.hu/xmleditor" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="project://.stylesheets/stylesheet_config.xsd">
    <stylesheet aggregatorClass="" inputExtension="xmlout" preprocessorClass="" resultExtension="html" xslFile="ReportWithMenu_HTML.xslt">
        <description>HTML report with TOC and menu</description>
    </stylesheet>
    <stylesheet aggregatorClass="" inputExtension="xmlout" preprocessorClass="" resultExtension="html" xslFile="Report_HTML.xslt">
        <description>Generate HTML Reports based on the selected Log (same as for PDF)
			resources</description>
    </stylesheet>
    <stylesheet aggregatorClass="" inputExtension="xmlout" preprocessorClass="" resultExtension="html" xslFile="Report_HTML_screenshots.xslt">
        <description>Generate HTML Reports based on the selected Log (same as for PDF)
			resources (results will appears as screenshots)</description>
    </stylesheet>
    <stylesheet aggregatorClass="" inputExtension="xmlout" preprocessorClass="" resultExtension="pdf" xslFile="Report_PDF.xslt">
        <description>Generate PDF Reports based on the selected Log (same as for HTML)
			resources</description>
    </stylesheet>
    <!--  stylesheet xslFile="Report_PDF_screenshots.xslt" inputExtension="xmlout"
		resultExtension="pdf" aggregatorClass="" preprocessorClass="">
		<description>Generate PDF Reports based on the selected Log (same as for HTML)
			resources (results will appears as screenshots)</description>
	</stylesheet>
-->
    <stylesheet aggregatorClass="" inputExtension="xhtml" preprocessorClass="" resultExtension="xhtml" xslFile="Utilty_of_Report_PDF.xslt">
        <description>[Not for direct usage] Works under the PDF Report
			Generator</description>
    </stylesheet>
    <!-- Deprecated style sheets, see JIRA TM-2455
	<stylesheet xslFile="DefectReport_HTML.xslt" inputExtension="xmlout"
		resultExtension="html" aggregatorClass="" preprocessorClass="">
		<description>Defect Report generation</description>
	</stylesheet>
	<stylesheet xslFile="DefectReport_PDF.xslt" inputExtension="xmlout"
		resultExtension="pdf" aggregatorClass="" preprocessorClass="">
		<description>Generate defect PDF Reports </description>
	</stylesheet>
	<stylesheet xslFile="PrintableReport_HTML.xslt" inputExtension="xmlout"
		resultExtension="html" aggregatorClass="" preprocessorClass="">
		<description>Generate Printable PDF Reports</description>
	</stylesheet>
	<stylesheet xslFile="PrintableReport_PDF.xslt" inputExtension="xmlout"
		resultExtension="pdf" aggregatorClass="" preprocessorClass="">
		<description>Generate Printable PDF Reports</description>
	</stylesheet>
	<stylesheet xslFile="ShortReport_HTML.xslt" inputExtension="xmlout"
		resultExtension="html" aggregatorClass="" preprocessorClass="">
		<description>Generate Short Printable HTML Reports</description>
	</stylesheet>
	<stylesheet xslFile="ShortReport_PDF.xslt" inputExtension="xmlout"
		resultExtension="pdf" aggregatorClass="" preprocessorClass="">
		<description>Generate Short Printable PDF Reports</description>
	</stylesheet>
	<stylesheet xslFile="T24BrowserStyleReport_HTML.xslt" inputExtension="xmlout"
		resultExtension="html" aggregatorClass="" preprocessorClass="">
		<description>Generate HTML Reports</description>
	</stylesheet>
-->
</stylesheetConfig>
